services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        UID: 1000
        GID: 1000
    container_name: debriefing_app
    volumes:
      - ../src:/var/www
    working_dir: /var/www
    depends_on:
    - db
    networks:
    - debriefing_net

  web:
    image: nginx:alpine
    container_name: debriefing_nginx
    ports: 
    - "8000:80"
    volumes:
    - ../src:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - app
    networks:
    - debriefing_net

  db:
    image: postgres:17
    container_name: debriefing_db
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    volumes:
    - debriefing_pgdata:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    networks:
    - debriefing_net
  pgadmin:
    image: dpage/pgadmin4
    container_name: debriefing_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "5051:80"
    depends_on:
    - db
    networks:
    - debriefing_net

networks:
  debriefing_net:
volumes:
  debriefing_pgdata: